name: Auto Assign to Security Project

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
env:
  MY_GITHUB_TOKEN: ${{ secrets.CC_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to SWG Project
    steps:
    - name: Assign NEW issues and NEW pull requests to SWG Project
      uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/orgs/openedx/projects/45'
